name: ORT Analyzer
on:
  workflow_dispatch:
jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Test ORT download
        run: |
          docker run --rm \
            -v $HOME:/home/ort \
            ghcr.io/oss-review-toolkit/ort:89.3.0 \
            download \
            --project-url https://github.com/WebGoat/WebGoat \
            -o /home/ort/out

    
