name: ORT Analyzer
on:
  workflow_dispatch:
jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Test ORT image
        run: docker run --rm ghcr.io/oss-review-toolkit/ort:89.3.0 --version

    
